apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    name: mariadb-service
    app: mariadb
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mariadb
  type: LoadBalancer 
  selector:
    name: mariadb-pod
    app: mariadb